import { StyleSheet } from "react-native";
import { Fonts } from "../../../types/Fonts";

export const loginStyles = StyleSheet.create({
	container: { flex: 1 },
	content: { flex: 1 },
	cabecalho: {
		flex: 0.4,
		backgroundColor: "#1A5D48",
		justifyContent: "center",
		alignItems: "center",
		paddingTop: 20,
	},
	logoContainer: { alignItems: "center" },
	logo: {
		width: 150,
		height: 150,
		marginBottom: 20,
		boxShadow: "0px 4px 8px rgba(0,0,0,0.3)",
		elevation: 8, // Android
	},
	bemvindo: {
		color: "#FFF",
		marginBottom: 8,
		textAlign: "center",
		fontFamily: Fonts.RobotoSlab.Black,
		fontSize: 28,
	},
	subtitulo: {
		fontSize: 20,
		color: "#B8D4C8",
		textAlign: "center",
		fontFamily: Fonts.RobotoSlab.Regular,
	},
	formContainer: {
		flex: 0.6,
		backgroundColor: "#F8F9FA",
		borderTopLeftRadius: 30,
		borderTopRightRadius: 30,
		paddingHorizontal: 24,
		paddingTop: 32,
		marginTop: -10,
	},
	card: {
		backgroundColor: "#FFF",
		borderRadius: 20,
		padding: 24,
		boxShadow: "0px 2px 12px rgba(0,0,0,0.1)",
		elevation: 5,
	},
	inputGroup: { marginBottom: 20 },
	inputLabel: {
		fontSize: 16,
		fontFamily: Fonts.RobotoSlab.Bold,
		color: "#1A5D48",
		marginBottom: 8,
	},
	inputContainer: {
		flexDirection: "row",
		alignItems: "center",
		backgroundColor: "#F5F5F5",
		borderRadius: 12,
		borderWidth: 2,
		borderColor: "#E0E0E0",
		height: 56,
		paddingHorizontal: 16,
	},
	inputIcon: { marginRight: 12 },
	textInput: {
		flex: 1,
		fontSize: 16,
		color: "#333",
		height: "100%",
		fontFamily: Fonts.DMSans.Bold,
	},
	eyeButton: { padding: 4 },
	loginButton: {
		backgroundColor: "#1A5D48",
		height: 56,
		borderRadius: 12,
		flexDirection: "row",
		justifyContent: "center",
		alignItems: "center",
		marginTop: 12,
		boxShadow: "0px 4px 8px rgba(26,93,72,0.3)",
		elevation: 6,
	},
	loginButtonDisabled: { opacity: 0.7 },
	loginButtonText: {
		color: "#FFF",
		fontSize: 18,
		fontFamily: Fonts.RobotoSlab.Bold,
		marginRight: 8,
	},
});